# Generated by Django 3.1.2 on 2020-11-05 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10)),
                ('fixed', models.BooleanField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('breed', models.CharField(default='American Bulldog', max_length=100)),
                ('condition', models.CharField(choices=[('Normal', 'Normal'), ('Injured', 'Injured'), ('Sick', 'Sick'), ('Nursing', 'Nursing'), ('Aggressive', 'Aggressive'), ('Aged', 'Aged'), ('Pregnant', 'Pregnant')], default='normal', max_length=40, verbose_name='intake condition')),
                ('intake_type', models.CharField(choices=[('Stray', 'Stray'), ('Owner Surrender', 'Owner Surrender'), ('Public Assist', 'Public Assist'), ('Euthanasia Request', 'Euthanasia Request')], default='stray', max_length=100)),
                ('coat_pattern', models.CharField(choices=[('none', 'None'), ('tricolor', 'Tricolor'), ('bicolor', 'Bicolor'), ('merle', 'Merle'), ('sable', 'Sable'), ('tick', 'Tick'), ('brindle', 'Brindle')], default='none', max_length=32)),
                ('primary_color', models.CharField(choices=[('none', 'None'), ('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('blue ', 'Blue'), ('red ', 'Red'), ('tan', 'Tan'), ('yellow', 'Yellow'), ('cream', 'Red'), ('gray', 'Gray'), ('orange', 'Orange'), ('buff', 'Buff'), ('gold', 'Gold'), ('silver', 'Silver')], default='none', max_length=32)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('mixed', models.BooleanField(default=False)),
                ('puppy', models.BooleanField(default=False)),
                ('bully', models.BooleanField(default=False, verbose_name='is this a bully breed?')),
                ('pred_outcome', models.CharField(max_length=50, null=True)),
                ('true_outcome', models.CharField(blank=True, choices=[('Adoption', 'Adoption'), ('Return to Owner', 'Return to Owner'), ('Transfer', 'Transfer'), ('Euthanasia', 'Euthanasia')], max_length=50, null=True)),
                ('kennel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dog.kennel', to_field='name')),
            ],
        ),
    ]
