# Generated by Django 3.1.2 on 2020-10-19 23:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10)),
                ('fixed', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('breed', models.CharField(default='American Bulldog', max_length=100)),
                ('condition', models.CharField(choices=[('normal', 'Normal'), ('injured', 'Injured'), ('sick', 'Sick'), ('nursing', 'Nursing'), ('ages', 'Aged'), ('pregnant', 'Pregnant')], default='normal', max_length=32)),
                ('intake_type', models.CharField(choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('public assist', 'Public Assist'), ('euthanasia request', 'Euthanasia Request')], default='stray', max_length=100)),
                ('coat_pattern', models.CharField(choices=[('none', 'None'), ('tricolor', 'Tricolor'), ('bicolor', 'Bicolor'), ('merle', 'Merle'), ('sable', 'Sable'), ('tick', 'Tick'), ('brindle', 'Brindle')], default='none', max_length=32)),
                ('primary_color', models.CharField(choices=[('none', 'None'), ('black', 'Black'), ('brown', 'Brown'), ('white', 'White'), ('blue ', 'Blue'), ('tan', 'Tan'), ('yellow', 'Yellow'), ('cream', 'Red'), ('tricolor', 'Tricolor'), ('merle', 'Merle'), ('sable', 'Sable'), ('tick', 'Tick'), ('brindle', 'Brindle')], default='none', max_length=32)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(20)])),
                ('mixed', models.BooleanField(default=False)),
                ('puppy', models.BooleanField(default=False)),
                ('bully', models.BooleanField(default=False)),
                ('kennel', models.ForeignKey(default='Default', on_delete=django.db.models.deletion.CASCADE, to='dog.kennel', to_field='name')),
                ('outcome', models.ManyToManyField(null=True, to='dog.Outcome')),
            ],
        ),
    ]
