# Generated by Django 3.1.2 on 2020-10-20 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='condition',
            field=models.CharField(choices=[('normal', 'Normal'), ('injured', 'Injured'), ('sick', 'Sick'), ('nursing', 'Nursing'), ('aged', 'Aged'), ('pregnant', 'Pregnant')], default='normal', max_length=32),
        ),
        migrations.AlterField(
            model_name='dog',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dog',
            name='outcome',
            field=models.ManyToManyField(blank=True, null=True, to='dog.Outcome'),
        ),
    ]
