# Generated by Django 3.1.2 on 2020-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='pred_outcome',
            field=models.CharField(default='No Outcome', max_length=50),
        ),
    ]
