# Generated by Django 3.1.2 on 2020-10-30 03:31

from django.db import migrations, models
import dog.models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0002_auto_20201029_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='pred_outcome',
            field=models.CharField(default=dog.models.Dog.predictOutcome, max_length=50),
        ),
    ]
