# Generated by Django 3.1.2 on 2020-10-21 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_auto_20201020_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)]),
        ),
    ]
