# Generated by Django 3.1.2 on 2020-11-05 23:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0003_auto_20201105_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='day',
            field=models.CharField(default='Sunday', max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Age (0 for less than one year old)'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Intake Time (MM/DD/YYYY HH:MM)'),
        ),
    ]
