# Generated by Django 3.1.2 on 2020-10-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_auto_20201024_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Injured', 'Injured'), ('Sick', 'Sick'), ('Nursing', 'Nursing'), ('Aggressive', 'Aggressive'), ('Aged', 'Aged'), ('Pregnant', 'Pregnant')], default='normal', max_length=40, verbose_name='intake condition'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='intake_type',
            field=models.CharField(choices=[('Stray', 'Stray'), ('Owner Surrender', 'Owner Surrender'), ('Public Assist', 'Public Assist'), ('Euthanasia Request', 'Euthanasia Request')], default='stray', max_length=100),
        ),
    ]
