# Generated by Django 3.1.2 on 2020-10-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0004_auto_20201021_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='condition',
            field=models.CharField(choices=[('normal', 'Normal'), ('injured', 'Injured'), ('sick', 'Sick'), ('nursing', 'Nursing'), ('aged', 'Aged'), ('pregnant', 'Pregnant')], default='normal', max_length=40),
        ),
        migrations.AlterField(
            model_name='dog',
            name='intake_type',
            field=models.CharField(choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('public assist', 'Public Assist'), ('Euthanasia Request', 'Euthanasia Request')], default='stray', max_length=100),
        ),
    ]
