# Generated by Django 3.1.2 on 2020-11-14 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0005_auto_20201113_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='checkout',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
