# Generated by Django 3.1.2 on 2020-10-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0005_auto_20201021_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='intake_type',
            field=models.CharField(choices=[('stray', 'Stray'), ('owner surrender', 'Owner Surrender'), ('public assist', 'Public Assist'), ('euthanasia request', 'Euthanasia Request')], default='stray', max_length=100),
        ),
    ]
